sudo: required

services:
  - docker

before_install:
  - docker build --rm -t fucompany/thumbd .
  - docker build --rm -t fucompany/thumbd -f Dockerfile.test .

script:
  - docker run fucompany/thumbd
