FROM mhart/alpine-node:6

# Install imagemagick & thumbd
RUN apk update
RUN apk add imagemagick git
RUN npm set registry https://registry.npmjs.org
RUN git clone https://github.com/mybigday/docker-thumbd.git /thumbd && \
    cd /thumbd && \
    # 2.19.0
    git checkout self
WORKDIR /thumbd
RUN npm i

CMD ["npm", "test"]
